export enum ErrorMessages {
  USERNAME_REQUIRED = 'no has insertado tu unsername',
  PASSWORD_REQUIRED = 'no has insertado tu password',
  NIVEL_REQUIRED = 'debes seleccionar un nivel',
  INVALID_NIVEL_YEAR = 'debes seleccion un año y un nivel',
  UNKNOW_ERROR = 'no se pudo realizar la operación',
  FALTAN_DATOS = 'te falta proporcionar mas información',
  INVALID_TOKEN = 'invalid or corrupted token',
  SERVER_401 = 'Request failed with status code 401',
  SESSION_EXPIRED = 'Es posible que tu sesión haya expirado',
  BAD_REQUEST = 'Petición inválida',
  UNAUTHORIZED = 'No tienes privilegios para hacer esta petición',
  INVALID_CREDENTIALS = 'Credenciales inválidas',
  NOT_FOUND = 'NO SE PUDO ENCONTRAR UNA RUTA PARA SU PETICIÓN',
  ERROR_500 = 'Hubo un problema procesando su petición, por favor inténtelo nuevamente o consulte con el administrador',
}
